name: BSD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: vmactions/freebsd-vm@v0
      with:
        prepare: |
          pkg install -y curl && curl https://sh.rustup.rs -sSf | sh -s -- -y
        run: ls $HOME/.cargo/bin/ && cargo build --release
    - name: Upload Built tunet
      uses: actions/upload-artifact@v3
      with:
        name: tunet_x64
        path: target/release/tunet
        
