name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: musl Toolchain
      run: sudo apt update && sudo apt install -y musl && curl -O https://musl.cc/mipsel-linux-musl-cross.tgz && tar xzf mipsel-linux-musl-cross.tgz && sudo cp mipsel-linux-musl-cross/bin/* /usr/bin/    
    - name: Rust Toolchain
      run: rustup target add mipsel-unknown-linux-musl
    
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    
    - name: Build
      run: CC_mipsel_unknown_linux_musl=mipsel-linux-musl-gcc CARGO_TARGET_MIPSEL_UNKNOWN_LINUX_MUSL_LINKER=mipsel-linux-musl-gcc cargo build --target mipsel-unknown-linux-musl --package tunet --release
    
    - name: Upload Built tunet
      uses: actions/upload-artifact@v3
      with:
        name: tunet
        path: target/mipsel-unknown-linux-musl/release/
