name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt install
      run: sudo apt update && sudo apt install gcc-mips-linux-gnu
    - name: Toolchain
      run: rustup target add mips-unknown-linux-gnu
    - name: Build
      run: CC_mipsel_openwrt_linux_gnu=mipsel-linux-gnu-gcc CARGO_TARGET_MIPS_OPENWRT_LINUX_GNU_LINKER=mipsel-linux-gnu-gcc cargo build --target mipsel-openwrt-linux-gnu --release
    - name: Upload Built tunet
      uses: actions/upload-artifact@v3
      with:
        name: tunet
        path: target/
