name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt install
      run: sudo apt update && sudo apt install gcc-mipsel-linux-gnu
    - name: Toolchain
      run: rustup target add mipsel-unknown-linux-gnu
    - name: Build
      run: CARGO_TARGET_MIPSEL_UNKNOWN_LINUX_GNU_LINKER="mipsel-linux-gnu-gcc" CARGO_TARGET_DIR="build/" cargo build --target mipsel-unknown-linux-gnu --package tunet
    - name: Upload Built tunet
      uses: actions/upload-artifact@v3
      with:
        name: tunet
        path: build/
