name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: musl Toolchain
      run: sudo apt update && sudo apt install musl && curl -O https://musl.cc/mipsel-linux-musl-cross.tgz && sudo tar xzf mipsel-linux-musl-cross.tgz --directory=/
    - name: Rust Toolchain
      run: rustup target add mipsel-unknown-linux-musl
    - name: Build
      run: CC_mipsel_unknown_linux_musl=mipsel-linux-musl-gcc CARGO_TARGET_MIPSEL_UNKNOWN_LINUX_MUSL_LINKER=mipsel-linux-musl-gcc cargo build --target mipsel-unknown-linux-musl --release
    - name: Upload Built tunet
      uses: actions/upload-artifact@v3
      with:
        name: tunet
        path: target/mipsel-unknown-linux-musl/release/
