name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install mips toolchains
      run: sudo apt update && sudo apt install -y gcc-mips-linux-gnu
    - name: Build
      run: rustup target add mips-unknown-linux-gnu && cargo build --target mips-unknown-linux-gnu --release
      
